apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m3gg0fe4a-nodejs 
  janus-idp.io/tekton: m3gg0fe4a-nodejs
  backstage.io/kubernetes-id: m3gg0fe4a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m3gg0fe4a-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  